import React from 'react';
import { Message, AgentType } from '../types';
import { AgentBadge } from './AgentBadge';
import ReactMarkdown from 'react-markdown'; // Assuming we can use standard markdown or just basic text

interface ChatMessageProps {
  message: Message;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.role === 'user';
  
  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex flex-col max-w-[85%] md:max-w-[70%] ${isUser ? 'items-end' : 'items-start'}`}>
        
        {/* Agent Badge for AI messages */}
        {!isUser && message.agent && (
          <div className="mb-2">
            <AgentBadge type={message.agent} />
          </div>
        )}

        <div 
          className={`px-5 py-4 rounded-2xl text-sm leading-relaxed shadow-sm
            ${isUser 
              ? 'bg-blue-600 text-white rounded-tr-none' 
              : 'bg-white border border-gray-100 text-gray-800 rounded-tl-none'
            }`}
        >
          {/* Text Content */}
          <div className="whitespace-pre-wrap">
             {message.content}
          </div>

          {/* Image Content (Medical Records) */}
          {message.metadata?.imageUrl && (
            <div className="mt-4 overflow-hidden rounded-lg border border-gray-200">
              <img src={message.metadata.imageUrl} alt="Medical visual" className="w-full h-auto object-cover" />
              <div className="p-2 bg-gray-50 text-xs text-gray-500">
                Generated by Gemini 2.5 Flash Image
              </div>
            </div>
          )}

          {/* Sources (Grounding) */}
          {message.metadata?.sources && message.metadata.sources.length > 0 && (
            <div className="mt-4 pt-3 border-t border-gray-100">
              <p className="text-xs font-semibold text-gray-500 mb-1">Sumber:</p>
              <ul className="space-y-1">
                {message.metadata.sources.map((src, idx) => (
                  <li key={idx}>
                    <a href={src.uri} target="_blank" rel="noreferrer" className="text-xs text-blue-500 hover:underline truncate block">
                      {src.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
        
        <span className="text-[10px] text-gray-400 mt-1 px-1">
          {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
    </div>
  );
};