import React from 'react';
import { Message } from '../types';
import { AgentBadge } from './AgentBadge';

interface ChatMessageProps {
  message: Message;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.role === 'user';
  
  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex flex-col max-w-[85%] md:max-w-[70%] ${isUser ? 'items-end' : 'items-start'}`}>
        
        {!isUser && message.agent && (
          <div className="mb-2">
            <AgentBadge type={message.agent} />
          </div>
        )}

        <div 
          className={`px-5 py-4 rounded-2xl text-sm leading-relaxed shadow-sm overflow-hidden
            ${isUser 
              ? 'bg-blue-600 text-white rounded-tr-none' 
              : 'bg-white border border-gray-100 text-gray-800 rounded-tl-none'
            }`}
        >
          <div className="whitespace-pre-wrap">
             {message.content}
          </div>

          {/* Veo Video Content */}
          {message.metadata?.videoUrl && (
            <div className="mt-4 rounded-lg overflow-hidden border border-gray-200 bg-black">
              <video controls autoPlay loop muted className="w-full h-auto aspect-video">
                <source src={message.metadata.videoUrl} type="video/mp4" />
                Your browser does not support the video tag.
              </video>
              <div className="p-2 bg-gray-50 text-[10px] text-gray-500 flex justify-between">
                <span>Generated by Veo 3.1</span>
                <span>720p • AI Generated</span>
              </div>
            </div>
          )}

          {/* Image Content */}
          {message.metadata?.imageUrl && (
            <div className="mt-4 overflow-hidden rounded-lg border border-gray-200">
              <img src={message.metadata.imageUrl} alt="Medical visual" className="w-full h-auto object-cover" />
              <div className="p-2 bg-gray-50 text-[10px] text-gray-500">
                Generated by Gemini 2.5 Flash Image
              </div>
            </div>
          )}

          {/* Sources */}
          {message.metadata?.sources && message.metadata.sources.length > 0 && (
            <div className="mt-4 pt-3 border-t border-gray-100">
              <p className="text-xs font-semibold text-gray-500 mb-1">Sumber Referensi:</p>
              <ul className="space-y-1">
                {message.metadata.sources.map((src, idx) => (
                  <li key={idx}>
                    <a href={src.uri} target="_blank" rel="noreferrer" className="text-xs text-blue-500 hover:underline truncate block">
                      {src.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
        
        <span className="text-[10px] text-gray-400 mt-1 px-1">
          {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
    </div>
  );
};